### ISSUE TITLE
Dublicated graph item

### ISSUE THREAD

**Issue by zgamedog** [SolarianZ/UnityPlayableGraphMonitorTool#15] opened 2023-09-06 08:35 UTC
![1111](https://github.com/SolarianZ/UnityPlayableGraphMonitorTool/assets/17020783/b70f2d37-d325-40be-9853-70592f8c1e10)

**Comment by zdirtywork** [comment] 2023-09-06 09:01
Hi, can you submit a simple project that reproduces this problem?

**Comment by SolarianZ** [comment] 2023-11-03 14:37
Close this issue because it cannot be reproduced and the requester has not responded for a long time.

**Closed by SolarianZ** 2023-11-03 14:37 UTC
